import type { OfferGoal } from '@/app/dashboard/offers/new/components/goal-step'

export type BusinessOfferTemplate = {
  title: string
  memberBenefit: string
  description: string
  goals: OfferGoal[]
  estimatedRetailValue: number
  estimatedBusinessCost: number
  requiresPurchase: boolean
  finePrint: string
  coachNote: string
}

const standardLimit =
  'RaiseHub members only. One redemption per member. Cannot be combined with other promotions.'

export const BUSINESS_OFFER_TEMPLATES: Record<string, BusinessOfferTemplate[]> = {
  'restaurant / food': [
    {
      title: 'Free appetizer with two entrées',
      memberBenefit: 'One selected appetizer free with two entrée purchases',
      description: 'Turn a full meal into a stronger-value RaiseHub experience without discounting the entrées.',
      goals: ['new-customers', 'average-purchase', 'repeat-customers'],
      estimatedRetailValue: 12,
      estimatedBusinessCost: 4,
      requiresPurchase: true,
      finePrint: `${standardLimit} Valid with two qualifying entrée purchases. Excludes premium appetizers.`,
      coachNote: 'Use a high-perceived-value appetizer with a controlled food cost.',
    },
    {
      title: 'Midweek dessert bonus',
      memberBenefit: 'Free selected dessert with a qualifying meal',
      description: 'Give members a reason to choose a slower weekday without lowering your core menu prices.',
      goals: ['slow-day', 'repeat-customers'],
      estimatedRetailValue: 9,
      estimatedBusinessCost: 3,
      requiresPurchase: true,
      finePrint: `${standardLimit} Valid on selected weekdays with a qualifying entrée purchase.`,
      coachNote: 'Attach the offer to your slower day instead of making it available all week.',
    },
    {
      title: 'RaiseHub family meal bundle',
      memberBenefit: 'Exclusive family bundle with a premium side or dessert included',
      description: 'Package existing items into an exclusive bundle that increases perceived value and total ticket size.',
      goals: ['average-purchase', 'new-customers'],
      estimatedRetailValue: 15,
      estimatedBusinessCost: 5,
      requiresPurchase: true,
      finePrint: `${standardLimit} Valid on the designated RaiseHub family bundle only.`,
      coachNote: 'Bundle existing high-margin items instead of discounting every item individually.',
    },
    {
      title: 'Try the new item bonus',
      memberBenefit: 'Complimentary selected add-on with the featured new menu item',
      description: 'Encourage trial of a new product while keeping the new item itself at full price.',
      goals: ['new-product'],
      estimatedRetailValue: 8,
      estimatedBusinessCost: 2,
      requiresPurchase: true,
      finePrint: `${standardLimit} Requires purchase of the featured item while supplies last.`,
      coachNote: 'Use a low-cost add-on to drive trial without teaching customers to wait for discounts.',
    },
  ],
  'food truck': [
    {
      title: 'Free side with any combo',
      memberBenefit: 'One selected side free with a combo purchase',
      description: 'A simple truck-friendly offer that feels valuable and keeps the main entrée at full price.',
      goals: ['new-customers', 'average-purchase', 'repeat-customers'],
      estimatedRetailValue: 7,
      estimatedBusinessCost: 2,
      requiresPurchase: true,
      finePrint: `${standardLimit} Valid with a qualifying combo. Selected sides only.`,
      coachNote: 'Sides usually create stronger perceived value than a small dollar discount.',
    },
    {
      title: 'Today’s stop special',
      memberBenefit: 'Free drink or upgrade at the featured location',
      description: 'Tie the reward to a specific stop so RaiseHub can help drive traffic where you are today.',
      goals: ['event-traffic', 'slow-day'],
      estimatedRetailValue: 5,
      estimatedBusinessCost: 1.5,
      requiresPurchase: true,
      finePrint: `${standardLimit} Valid only at the listed location and time with an entrée purchase.`,
      coachNote: 'Make the offer location-specific so it supports the route you actually need traffic at.',
    },
    {
      title: 'RaiseHub event combo',
      memberBenefit: 'Exclusive entrée, side, and drink event bundle',
      description: 'Give event visitors one easy bundle to order while protecting speed and margin.',
      goals: ['event-traffic', 'average-purchase'],
      estimatedRetailValue: 10,
      estimatedBusinessCost: 3,
      requiresPurchase: true,
      finePrint: `${standardLimit} Valid during the designated event window on the RaiseHub combo only.`,
      coachNote: 'Keep the bundle operationally simple so it does not slow the line.',
    },
    {
      title: 'New menu item upgrade',
      memberBenefit: 'Free selected topping or side with the new featured item',
      description: 'Drive trial of a new menu item without discounting the entrée itself.',
      goals: ['new-product'],
      estimatedRetailValue: 6,
      estimatedBusinessCost: 1.5,
      requiresPurchase: true,
      finePrint: `${standardLimit} Requires purchase of the featured menu item.`,
      coachNote: 'Use a low-cost upgrade to make the new item feel special.',
    },
  ],
  'salon / beauty': [
    {
      title: 'Free conditioning treatment with color',
      memberBenefit: 'Complimentary conditioning treatment with a qualifying color service',
      description: 'Add a premium-feeling treatment instead of discounting stylist time.',
      goals: ['new-customers', 'appointments', 'repeat-customers'],
      estimatedRetailValue: 20,
      estimatedBusinessCost: 5,
      requiresPurchase: true,
      finePrint: `${standardLimit} Valid with selected color services and participating stylists.`,
      coachNote: 'Protect labor revenue by using a low-product-cost add-on.',
    },
    {
      title: 'Midweek service upgrade',
      memberBenefit: 'Complimentary selected upgrade on a midweek appointment',
      description: 'Shift demand into a slower appointment window while keeping service prices intact.',
      goals: ['slow-day', 'appointments'],
      estimatedRetailValue: 15,
      estimatedBusinessCost: 4,
      requiresPurchase: true,
      finePrint: `${standardLimit} Valid during selected weekday appointment windows only.`,
      coachNote: 'Use availability windows you actually want to fill.',
    },
    {
      title: 'Bring-a-friend beauty bonus',
      memberBenefit: 'Both guests receive a selected complimentary add-on',
      description: 'Turn one client visit into two appointments without deeply discounting either core service.',
      goals: ['new-customers', 'repeat-customers'],
      estimatedRetailValue: 18,
      estimatedBusinessCost: 5,
      requiresPurchase: true,
      finePrint: `${standardLimit} Both guests must book qualifying services in the promotional window.`,
      coachNote: 'Choose fast add-ons that do not disrupt the appointment schedule.',
    },
    {
      title: 'Featured treatment bonus',
      memberBenefit: 'Complimentary premium treatment with the featured service',
      description: 'Use a high-value add-on to introduce a new service or product line.',
      goals: ['new-product'],
      estimatedRetailValue: 16,
      estimatedBusinessCost: 4,
      requiresPurchase: true,
      finePrint: `${standardLimit} Valid with the designated featured service only.`,
      coachNote: 'Keep the featured service at full price and add value around it.',
    },
  ],
  automotive: [
    {
      title: 'Free tire rotation with oil change',
      memberBenefit: 'Complimentary tire rotation with a qualifying oil change',
      description: 'A familiar, useful add-on that encourages a paid maintenance visit.',
      goals: ['new-customers', 'repeat-customers', 'average-purchase'],
      estimatedRetailValue: 25,
      estimatedBusinessCost: 8,
      requiresPurchase: true,
      finePrint: `${standardLimit} Valid with qualifying oil change. Excludes specialty vehicles where noted.`,
      coachNote: 'Bundle labor-efficient maintenance tasks with a paid service.',
    },
    {
      title: 'Slow-day vehicle check',
      memberBenefit: 'Complimentary seasonal inspection with a qualifying service',
      description: 'Use inspection capacity on a slower day while creating opportunities for legitimate follow-up work.',
      goals: ['slow-day'],
      estimatedRetailValue: 30,
      estimatedBusinessCost: 8,
      requiresPurchase: true,
      finePrint: `${standardLimit} Valid on selected days with a qualifying paid service. Inspection does not include repairs.`,
      coachNote: 'Keep diagnostic scope clear and avoid open-ended free labor.',
    },
    {
      title: 'Free alignment check with tire purchase',
      memberBenefit: 'Complimentary alignment check with qualifying tire purchase',
      description: 'Add useful value to a higher-ticket purchase without discounting the tires.',
      goals: ['average-purchase', 'new-customers'],
      estimatedRetailValue: 20,
      estimatedBusinessCost: 5,
      requiresPurchase: true,
      finePrint: `${standardLimit} Requires qualifying tire purchase. Alignment service, if needed, is separate.`,
      coachNote: 'Use a low-cost check that can support appropriate follow-up service.',
    },
  ],
  'retail / boutique': [
    {
      title: 'Free accessory with $50 purchase',
      memberBenefit: 'Selected accessory free with a $50 qualifying purchase',
      description: 'Reward a larger basket with a high-margin item instead of discounting the whole purchase.',
      goals: ['average-purchase', 'new-customers', 'repeat-customers'],
      estimatedRetailValue: 15,
      estimatedBusinessCost: 4,
      requiresPurchase: true,
      finePrint: `${standardLimit} Qualifying purchase threshold applies. Selected accessories only.`,
      coachNote: 'Choose an accessory with strong perceived value and controlled cost.',
    },
    {
      title: 'RaiseHub exclusive bundle',
      memberBenefit: 'Members-only product bundle at a better combined value',
      description: 'Create something customers cannot get from your normal sale rack or email signup.',
      goals: ['new-customers', 'new-product'],
      estimatedRetailValue: 18,
      estimatedBusinessCost: 6,
      requiresPurchase: true,
      finePrint: `${standardLimit} Available on the designated RaiseHub bundle while supplies last.`,
      coachNote: 'Use a unique bundle rather than duplicating a public discount.',
    },
    {
      title: 'Second item 50% off',
      memberBenefit: 'Buy one qualifying item and receive a second selected item at 50% off',
      description: 'Encourage multi-item purchases while limiting the discount to the lower-cost item.',
      goals: ['average-purchase', 'slow-day'],
      estimatedRetailValue: 12,
      estimatedBusinessCost: 5,
      requiresPurchase: true,
      finePrint: `${standardLimit} Discount applies to the lower-priced eligible item. Exclusions may apply.`,
      coachNote: 'Protect margin by defining eligible items and applying the discount to the lower-priced item.',
    },
  ],
  'fitness / wellness': [
    {
      title: 'Free personal training introduction',
      memberBenefit: 'Complimentary introductory training session with a qualifying pass or membership',
      description: 'Let members experience a premium service that can convert into ongoing training.',
      goals: ['new-customers', 'appointments'],
      estimatedRetailValue: 35,
      estimatedBusinessCost: 12,
      requiresPurchase: true,
      finePrint: `${standardLimit} New training clients only. Advance booking required.`,
      coachNote: 'Use an introductory service that can lead to recurring revenue.',
    },
    {
      title: 'Bring a friend free',
      memberBenefit: 'One guest visit free with a member visit',
      description: 'Turn an existing customer into a warm introduction without discounting membership dues.',
      goals: ['new-customers', 'repeat-customers'],
      estimatedRetailValue: 18,
      estimatedBusinessCost: 4,
      requiresPurchase: false,
      finePrint: `${standardLimit} Guest must be a first-time or eligible returning visitor. Reservation may be required.`,
      coachNote: 'Use capacity-controlled guest access rather than an ongoing membership discount.',
    },
    {
      title: 'Off-peak premium class bonus',
      memberBenefit: 'Complimentary selected premium class during an off-peak window',
      description: 'Fill underused class capacity with a high-perceived-value experience.',
      goals: ['slow-day', 'new-product'],
      estimatedRetailValue: 22,
      estimatedBusinessCost: 5,
      requiresPurchase: false,
      finePrint: `${standardLimit} Valid for selected classes and times while space is available.`,
      coachNote: 'Target classes with open capacity so the marginal fulfillment cost stays low.',
    },
  ],
  'home services': [
    {
      title: 'Complimentary premium add-on with booked service',
      memberBenefit: 'Selected premium add-on included with a qualifying booked service',
      description: 'Increase perceived value without reducing the price of skilled labor.',
      goals: ['new-customers', 'appointments', 'average-purchase'],
      estimatedRetailValue: 25,
      estimatedBusinessCost: 7,
      requiresPurchase: true,
      finePrint: `${standardLimit} Requires a qualifying completed service. Add-on varies by service type.`,
      coachNote: 'Use a low-material-cost add-on and keep labor-heavy work at full price.',
    },
    {
      title: 'Slow-day priority upgrade',
      memberBenefit: 'Complimentary priority scheduling or service upgrade on selected days',
      description: 'Move flexible customers into open appointment windows with a benefit that costs little to fulfill.',
      goals: ['slow-day', 'appointments'],
      estimatedRetailValue: 20,
      estimatedBusinessCost: 3,
      requiresPurchase: true,
      finePrint: `${standardLimit} Valid only for selected appointment windows and service areas.`,
      coachNote: 'Use calendar capacity as the value instead of discounting the job.',
    },
    {
      title: 'Seasonal service bonus',
      memberBenefit: 'Complimentary seasonal check or maintenance add-on with service',
      description: 'Pair a timely maintenance benefit with a paid visit to drive seasonal demand.',
      goals: ['repeat-customers', 'new-product'],
      estimatedRetailValue: 30,
      estimatedBusinessCost: 8,
      requiresPurchase: true,
      finePrint: `${standardLimit} Scope is limited to the listed seasonal check or add-on.`,
      coachNote: 'Keep the free scope tightly defined so it cannot turn into open-ended labor.',
    },
  ],
  'medical / dental': [
    {
      title: 'Take-home care kit with qualifying visit',
      memberBenefit: 'Complimentary selected take-home care kit after a qualifying visit',
      description: 'Add non-clinical value around a completed visit without changing covered-service pricing.',
      goals: ['new-customers', 'repeat-customers'],
      estimatedRetailValue: 15,
      estimatedBusinessCost: 5,
      requiresPurchase: true,
      finePrint: `${standardLimit} Subject to practice policy, eligibility, and applicable healthcare or insurance rules.`,
      coachNote: 'Keep promotions separate from insured or regulated clinical pricing and verify local rules.',
    },
    {
      title: 'New-patient comfort package',
      memberBenefit: 'Complimentary comfort or welcome package with an eligible first visit',
      description: 'Make the first experience feel more welcoming with a low-cost non-clinical benefit.',
      goals: ['new-customers'],
      estimatedRetailValue: 18,
      estimatedBusinessCost: 5,
      requiresPurchase: true,
      finePrint: `${standardLimit} New eligible patients only. Subject to practice and payer rules.`,
      coachNote: 'Use non-clinical extras and avoid promises about treatment outcomes.',
    },
    {
      title: 'Off-peak scheduling perk',
      memberBenefit: 'Selected non-clinical perk for appointments in designated open windows',
      description: 'Encourage flexible scheduling without discounting professional care.',
      goals: ['slow-day', 'appointments'],
      estimatedRetailValue: 12,
      estimatedBusinessCost: 3,
      requiresPurchase: true,
      finePrint: `${standardLimit} Valid only for eligible appointments and subject to practice policy.`,
      coachNote: 'Use a scheduling perk rather than changing regulated or insured service pricing.',
    },
  ],
  entertainment: [
    {
      title: 'Free premium upgrade with admission',
      memberBenefit: 'Selected premium upgrade included with qualifying admission',
      description: 'Add a memorable perk while keeping the core admission price intact.',
      goals: ['new-customers', 'average-purchase', 'repeat-customers'],
      estimatedRetailValue: 12,
      estimatedBusinessCost: 3,
      requiresPurchase: true,
      finePrint: `${standardLimit} Valid with qualifying admission and selected upgrade options.`,
      coachNote: 'Choose an upgrade with spare capacity or low marginal cost.',
    },
    {
      title: 'Weekday bonus experience',
      memberBenefit: 'Complimentary selected add-on during a designated weekday window',
      description: 'Use an experience add-on to shift traffic into slower periods.',
      goals: ['slow-day', 'event-traffic'],
      estimatedRetailValue: 15,
      estimatedBusinessCost: 4,
      requiresPurchase: true,
      finePrint: `${standardLimit} Valid only on listed days and times with qualifying admission.`,
      coachNote: 'Tie the value to the exact time window you want to fill.',
    },
    {
      title: 'Group visit bonus',
      memberBenefit: 'Complimentary group add-on with a qualifying party size',
      description: 'Encourage larger groups with one shared high-value extra.',
      goals: ['average-purchase', 'event-traffic'],
      estimatedRetailValue: 20,
      estimatedBusinessCost: 5,
      requiresPurchase: true,
      finePrint: `${standardLimit} Minimum party size and reservation requirements may apply.`,
      coachNote: 'Reward the larger transaction instead of discounting every admission.',
    },
  ],
  'pet services': [
    {
      title: 'Free nail trim with grooming',
      memberBenefit: 'Complimentary nail trim with a qualifying grooming service',
      description: 'Add a useful pet-care extra without lowering the grooming service price.',
      goals: ['new-customers', 'appointments', 'repeat-customers'],
      estimatedRetailValue: 15,
      estimatedBusinessCost: 4,
      requiresPurchase: true,
      finePrint: `${standardLimit} Valid with qualifying grooming service and subject to pet safety requirements.`,
      coachNote: 'Use a short add-on that fits naturally into the booked service.',
    },
    {
      title: 'Slow-day pet care upgrade',
      memberBenefit: 'Complimentary selected add-on on designated slower days',
      description: 'Fill open appointment or daycare capacity with a low-cost extra.',
      goals: ['slow-day', 'appointments'],
      estimatedRetailValue: 12,
      estimatedBusinessCost: 3,
      requiresPurchase: true,
      finePrint: `${standardLimit} Valid on selected days and eligible services only.`,
      coachNote: 'Limit the offer to days and services where you have real capacity.',
    },
    {
      title: 'New service trial bonus',
      memberBenefit: 'Complimentary trial add-on with the featured pet service',
      description: 'Introduce a new service by adding value instead of discounting the service itself.',
      goals: ['new-product'],
      estimatedRetailValue: 14,
      estimatedBusinessCost: 4,
      requiresPurchase: true,
      finePrint: `${standardLimit} Requires purchase of the featured eligible service.`,
      coachNote: 'Keep the new service at full price and use a low-cost trial add-on.',
    },
  ],
  'professional services': [
    {
      title: 'Complimentary follow-up session',
      memberBenefit: 'One selected follow-up session included with a qualifying engagement',
      description: 'Increase confidence and value without discounting the initial professional work.',
      goals: ['new-customers', 'repeat-customers'],
      estimatedRetailValue: 50,
      estimatedBusinessCost: 15,
      requiresPurchase: true,
      finePrint: `${standardLimit} Scope and duration of the included follow-up must be defined in advance.`,
      coachNote: 'Define the follow-up scope tightly so the benefit remains sustainable.',
    },
    {
      title: 'Priority turnaround upgrade',
      memberBenefit: 'Complimentary priority turnaround on an eligible service',
      description: 'Use scheduling priority as a premium benefit when capacity allows.',
      goals: ['appointments', 'slow-day', 'new-customers'],
      estimatedRetailValue: 40,
      estimatedBusinessCost: 8,
      requiresPurchase: true,
      finePrint: `${standardLimit} Availability and eligible services vary. Does not guarantee a specific outcome.`,
      coachNote: 'Offer speed only when workload allows; do not promise results you cannot control.',
    },
    {
      title: 'Premium resource package included',
      memberBenefit: 'Complimentary templates, checklist, or resource package with service',
      description: 'Add scalable value around your expertise without reducing your professional fee.',
      goals: ['new-product', 'average-purchase'],
      estimatedRetailValue: 30,
      estimatedBusinessCost: 3,
      requiresPurchase: true,
      finePrint: `${standardLimit} Included resources are informational and tied to the qualifying service.`,
      coachNote: 'Reusable resources can deliver strong customer value at very low marginal cost.',
    },
  ],
  'mobile business': [
    {
      title: 'Route-day service bonus',
      memberBenefit: 'Complimentary selected add-on when booking on the featured route day',
      description: 'Concentrate demand along an existing route instead of creating extra travel.',
      goals: ['appointments', 'slow-day', 'event-traffic'],
      estimatedRetailValue: 20,
      estimatedBusinessCost: 5,
      requiresPurchase: true,
      finePrint: `${standardLimit} Valid only in the listed service area and route window.`,
      coachNote: 'Use geography and schedule to protect travel time and fuel cost.',
    },
    {
      title: 'Group booking bonus',
      memberBenefit: 'Complimentary upgrade when multiple nearby customers book together',
      description: 'Reward route efficiency by turning one trip into multiple paid services.',
      goals: ['average-purchase', 'new-customers'],
      estimatedRetailValue: 25,
      estimatedBusinessCost: 6,
      requiresPurchase: true,
      finePrint: `${standardLimit} Minimum qualifying bookings and service-area restrictions apply.`,
      coachNote: 'Tie the benefit to route density so the economics improve as the offer is used.',
    },
    {
      title: 'Featured location special',
      memberBenefit: 'Selected premium add-on at today’s featured location',
      description: 'Drive customers to the location where the mobile business is already operating.',
      goals: ['event-traffic', 'repeat-customers'],
      estimatedRetailValue: 15,
      estimatedBusinessCost: 4,
      requiresPurchase: true,
      finePrint: `${standardLimit} Valid only at the posted location and time.`,
      coachNote: 'Make location and time explicit so customers know exactly where the offer works.',
    },
  ],
  'pop-up / event vendor': [
    {
      title: 'Event-only bundle',
      memberBenefit: 'RaiseHub-exclusive event bundle with a premium add-on',
      description: 'Create a fast, event-specific purchase that feels special and is easy to fulfill.',
      goals: ['event-traffic', 'average-purchase', 'new-customers'],
      estimatedRetailValue: 12,
      estimatedBusinessCost: 4,
      requiresPurchase: true,
      finePrint: `${standardLimit} Valid only at the designated event while supplies last.`,
      coachNote: 'Keep the event bundle simple enough for high-volume service.',
    },
    {
      title: 'Spend-threshold event gift',
      memberBenefit: 'Complimentary selected item with a qualifying event purchase',
      description: 'Encourage a larger basket without discounting every product.',
      goals: ['average-purchase', 'event-traffic'],
      estimatedRetailValue: 10,
      estimatedBusinessCost: 3,
      requiresPurchase: true,
      finePrint: `${standardLimit} Minimum purchase threshold and selected gift apply.`,
      coachNote: 'Choose a gift with strong perceived value and enough event inventory.',
    },
    {
      title: 'Limited-drop member bonus',
      memberBenefit: 'Exclusive add-on or early-access perk with the featured release',
      description: 'Give RaiseHub members a reason to seek out a new product or limited drop.',
      goals: ['new-product', 'repeat-customers'],
      estimatedRetailValue: 10,
      estimatedBusinessCost: 2,
      requiresPurchase: true,
      finePrint: `${standardLimit} Valid with the featured release while supplies last.`,
      coachNote: 'Use exclusivity or access rather than deep price cuts on limited inventory.',
    },
  ],
  other: [
    {
      title: 'Complimentary premium add-on',
      memberBenefit: 'Selected premium add-on included with a qualifying purchase',
      description: 'Add meaningful value around the core purchase without discounting everything.',
      goals: ['new-customers', 'repeat-customers', 'average-purchase'],
      estimatedRetailValue: 15,
      estimatedBusinessCost: 4,
      requiresPurchase: true,
      finePrint: standardLimit,
      coachNote: 'Choose an add-on with high perceived value and low fulfillment cost.',
    },
    {
      title: 'Slow-day member bonus',
      memberBenefit: 'Selected member-only upgrade during a designated slow period',
      description: 'Use timing rather than deep discounting to bring customers in when you have capacity.',
      goals: ['slow-day'],
      estimatedRetailValue: 12,
      estimatedBusinessCost: 3,
      requiresPurchase: true,
      finePrint: `${standardLimit} Valid only during the listed promotional window.`,
      coachNote: 'Restrict the offer to the time you actually want to grow.',
    },
    {
      title: 'Featured product or service bonus',
      memberBenefit: 'Complimentary selected extra with the featured product or service',
      description: 'Encourage trial of something new while keeping the featured item at full value.',
      goals: ['new-product'],
      estimatedRetailValue: 12,
      estimatedBusinessCost: 3,
      requiresPurchase: true,
      finePrint: standardLimit,
      coachNote: 'Add value around the new item rather than discounting it immediately.',
    },
  ],
}

export function getBusinessOfferTemplates(category: string) {
  const normalized = category.trim().toLowerCase()
  return (
    BUSINESS_OFFER_TEMPLATES[normalized] ??
    BUSINESS_OFFER_TEMPLATES.other
  )
}
